task:

  name: "Setting Up, Syncing, Building and Uploading..."

  timeout_in: 4h

  container:

      image: docker

      cpu: 8

      memory: 32G
      
  Build-Env-Setup_script:

       - export DEBIAN_FRONTEND=noninteractive

       - pacman -S sudo

       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

       - pacman -S tzdata

       - dpkg-reconfigure --frontend noninteractive tzdata

       - sudo pacman -S git aria2 curl wget rsync zip unzip lzma cpio ccache neofetch -y

       - sudo pacman -s python2 -y

       - sudo ln -sf /usr/bin/python2 /usr/bin/python

       - git config --global user.name "OmarAlCoptan"

       - git config --global user.email "omarcoptan9@gmail.com"

       - git clone https://github.com/akhilnarang/scripts.git ~/scripts

       - cd ~/scripts

       - sudo bash setup/android_build_env.sh

       - cd 
       
       - mkdir -p /tmp/rom

       - cd /tmp/rom

       - repo init -q --no-repo-verify --depth=1 -u https://github.com/Evolution-X/manifest -b tiramisu -g default,-device,-mips,-darwin,-notdefault

       - git clone https://github.com/OmarAlCoptan/local_manifest.git --depth 1 -b evo .repo/local_manifests

       - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

       - . build/envsetup.sh
  
       - lunch evolution_lavender-userdebug

       - export CCACHE_DIR=/tmp/ccache

       - export CCACHE_EXEC=$(which ccache)

       - export USE_CCACHE=1

       - ccache -M 20G
    
       - ccache -o compression=true

       - ccache -z

       - make api-stubs-docs || echo no problem

       - make system-api-stubs-docs || echo no problem

       - make test-api-stubs-docs || echo no problem

       - mka evolution


Upload_script:

      - cd out/target/product/"$DEVICE"

      - ls -lh

      - pwd

      - chmod 777 *

      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "

      - echo " "

      - echo "============================"

      - echo "Build Uploaded!"

      - echo "Please see the link Below-  "

      - echo "----------------------------"

      - cat link.txt && echo " "

      - echo "============================"
  
